# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.Room'),
        ),
    ]
